[package]
name = "week4"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["mybase","mylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mylib = {path="./mylib"}

