name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: commit info 
      run: git rev-parse HEAD && git log --format=%B -n 1 $latest_commit
    - name: load env
      run: env
